- name: Create Jenkins jobs
  hosts: localhost
  connection: local
  vars:
    jobs:
      - roboshop-terraform
      - cart
      - catalogue
      - shipping
      - user
      - payment
  roles:
    - jenkins-jobs
