- name: Create Jenkins jobs
  hosts: localhost
  connection: local
  vars:
    sp_jobs:
      - roboshop-terraform
    mp_jobs:
      - cart
      - catalogue
      - shipping
      - user
      - payment
      - frontend
  roles:
    - jenkins-jobs
